apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-front-app
  name: udagram-front-app-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-front-app-svc
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: udagram-front-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}